---
server:
  port: 8761

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: false

eureka:
  instance:
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: http://localhost:8761/eureka/
