info:
  name: "Configuration Server"
app:
  name: ConfigApp

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qiuzhanghua/cloud-config-sample.git


#  file://${user.home}/spring-cloud/config-repo
#  git@github.com:qiuzhanghua/cloud-config-sample.git
#  https://github.com/qiuzhanghua/cloud-config-sample.git